import { Book, Category, Review } from './types';

export const CATEGORIES: Category[] = [
  { id: 'fantasy', name: 'Fantasy', icon: '🏰' },
  { id: 'romance', name: 'Romance', icon: '🌹' },
  { id: 'mystery', name: 'Mystery', icon: '🔍' },
  { id: 'sci-fi', name: 'Sci-Fi', icon: '🪐' },
  { id: 'horror', name: 'Horror', icon: '🕯️' },
  { id: 'manga', name: 'Manga', icon: '⛩️' },
  { id: 'self-help', name: 'Self Help', icon: '🍃' },
  { id: 'poetry', name: 'Poetry', icon: '📜' },
  { id: 'classics', name: 'Classics', icon: '🏛️' },
  { id: 'young-adult', name: 'Young Adult', icon: '🎒' },
];

export const BOOKS: Book[] = [
  // Fantasy
  {
    id: '1',
    title: 'The Enchanted Forest',
    author: 'Elara Moonwhisper',
    price: 20.99,
    discountPrice: 14.99,
    discountPercent: '-29%',
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=600',
    category: 'fantasy',
    isBestSeller: true,
    bookType: 'ebook',
  },
  {
    id: '2',
    title: 'The Shadow Heir',
    author: 'L. J. Andrews',
    price: 18.99,
    discountPrice: 12.49,
    discountPercent: '-34%',
    rating: 4.7,
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=600',
    category: 'fantasy',
    isBestSeller: true,
    bookType: 'physical',
  },
  {
    id: '3',
    title: 'The Lost Kingdom',
    author: 'M. R. Hawthorne',
    price: 22.99,
    discountPrice: 15.99,
    discountPercent: '-30%',
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&q=80&w=600',
    category: 'fantasy',
    bookType: 'ebook',
  },
  // Romance
  {
    id: '4',
    title: 'A Thousand Promises',
    author: 'Clara Voss',
    price: 16.99,
    discountPrice: 11.99,
    discountPercent: '-29%',
    rating: 4.6,
    coverImage: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&q=80&w=600',
    category: 'romance',
    bookType: 'physical',
  },
  {
    id: '5',
    title: 'Wisteria Lane',
    author: 'Sophie Thorne',
    price: 14.99,
    rating: 4.5,
    coverImage: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&q=80&w=600',
    category: 'romance',
    bookType: 'ebook',
  },
  // Mystery
  {
    id: '6',
    title: 'The Silent Grove',
    author: 'R. K. Sterling',
    price: 19.99,
    discountPrice: 15.99,
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1531988042231-d39a9cc12a9a?auto=format&fit=crop&q=80&w=600',
    category: 'mystery',
    isBestSeller: true,
    bookType: 'physical',
  },
  {
    id: '7',
    title: 'Whispers in the Mist',
    author: 'Thomas Hardie',
    price: 17.50,
    rating: 4.2,
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=600',
    category: 'mystery',
    bookType: 'ebook',
  },
  // Sci-Fi
  {
    id: '8',
    title: 'Nebula Protocol',
    author: 'Jax Vansen',
    price: 25.99,
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&q=80&w=600',
    category: 'sci-fi',
    bookType: 'physical',
  },
  {
    id: '9',
    title: 'Solar Drift',
    author: 'Elena Kostic',
    price: 21.00,
    rating: 4.6,
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=600',
    category: 'sci-fi',
    isNew: true,
    bookType: 'ebook',
  },
  // Horror
  {
    id: '10',
    title: 'The Haunting of Hill House',
    author: 'Shirley Jackson',
    price: 15.99,
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&q=80&w=600',
    category: 'horror',
    isBestSeller: true,
    bookType: 'physical',
  },
  // Manga
  {
    id: '11',
    title: 'Spirit Warrior Vol. 1',
    author: 'T. Yamamoto',
    price: 12.99,
    rating: 4.7,
    coverImage: 'https://images.unsplash.com/photo-1589998059171-988d887df646?auto=format&fit=crop&q=80&w=600',
    category: 'manga',
    bookType: 'physical',
  },
];

export const READING_BOOKS: Book[] = [
  {
    id: 'r1',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    price: 0,
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=200',
    category: 'Fantasy',
    progress: 65,
    bookType: 'ebook',
  },
  {
    id: 'r2',
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    price: 0,
    rating: 4.7,
    coverImage: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&q=80&w=200',
    category: 'Mystery',
    progress: 28,
    bookType: 'ebook',
  },
  {
    id: 'r3',
    title: 'Dune',
    author: 'Frank Herbert',
    price: 0,
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=200',
    category: 'Sci-Fi',
    progress: 45,
    bookType: 'ebook',
  },
];

export const NEW_ARRIVALS: Book[] = [
  {
    id: 'n1',
    title: 'The Atlas Paradox',
    author: 'Olivia Blake',
    price: 24.99,
    rating: 4.5,
    coverImage: 'https://images.unsplash.com/photo-1543004218-ee141104332f?auto=format&fit=crop&q=80&w=400',
    category: 'Fantasy',
    isNew: true,
    bookType: 'physical',
  },
  {
    id: 'n2',
    title: 'Ivy & Bone',
    author: 'Juno Stewart',
    price: 21.99,
    rating: 4.3,
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400',
    category: 'Fantasy',
    isNew: true,
    bookType: 'ebook',
  },
  {
    id: 'n3',
    title: 'A Curse of Thorns',
    author: 'L. K. Wilder',
    price: 22.50,
    rating: 4.6,
    coverImage: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&q=80&w=400',
    category: 'Fantasy',
    isNew: true,
    bookType: 'physical',
  },
];

export const REVIEWS: Review[] = [
  {
    id: '1',
    userName: 'Alice Penhaligon',
    avatar: 'https://i.pravatar.cc/150?u=alice',
    rating: 5,
    comment: 'The Midnight Forest is absolutely enchanting! The world-building felt so real and cozy.',
  },
  {
    id: '2',
    userName: 'Robin Oakheart',
    avatar: 'https://i.pravatar.cc/150?u=robin',
    rating: 4,
    comment: 'A wonderful escape. The storytelling is like a warm hug on a rainy day.',
  },
];
